name: Ads Scheduler

on:
  workflow_dispatch:
 

jobs:
  post-ad:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: IDK
        env: 
            REPO_VAR_ONE: ${{ vars.AD_1}}
            REPO_VAR_TWO: ${{ vars.DISCORD_URLS}}
            SECRET_VAR: ${{ secrets.ACCOUNT_1_TOKEN}}
        run: |
          python3 1.py 
 
