jobs:
  post-ad:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List files in directory
        run: ls -R

      - name: Set Ad Variables
        run: |
          echo "AD_CONTENT=${{ matrix.ad.content }}" >> $GITHUB_ENV
          echo "ACCOUNT_TOKEN=${{ secrets[matrix.ad.token] }}" >> $GITHUB_ENV
          echo "DISCORD_URLS=${{ secrets.DISCORD_URLS }}" >> $GITHUB_ENV

      - name: Debug Variables
        run: |
          echo "Ad Content: ${{ env.AD_CONTENT }}"
          echo "Account Token: [HIDDEN]"
          echo "Discord URLs: [HIDDEN]"

      - name: Post Ad
        run: python3 1.py "${{ env.AD_CONTENT }}" "${{ env.ACCOUNT_TOKEN }}" "${{ env.DISCORD_URLS }}"