name: Ads Scheduler

on:
  workflow_dispatch:  # Allow manual triggers
  schedule:
    - cron: "0 0 * * *"  # 00:00 - Ad 1
    - cron: "0 2 * * *"  # 02:00 - Ad 2
    - cron: "0 4 * * *"  # 04:00 - Ad 3
    - cron: "0 6 * * *"  # 06:00 - Ad 4
    - cron: "0 8 * * *"  # 08:00 - Ad 5
    - cron: "0 10 * * *" # 10:00 - Ad 6
    - cron: "0 12 * * *" # 12:00 - Ad 7
    - cron: "0 14 * * *" # 14:00 - Ad 8
    - cron: "0 16 * * *" # 16:00 - Ad 9
    - cron: "0 18 * * *" # 18:00 - Ad 10
    - cron: "0 20 * * *" # 20:00 - Ad 11
    - cron: "0 22 * * *" # 22:00 - Ad 12

jobs:
  post-ad:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        schedule:
          - "0 0 * * *"
          - "0 2 * * *"
          - "0 4 * * *"
          - "0 6 * * *"
          - "0 8 * * *"
          - "0 10 * * *"
          - "0 12 * * *"
          - "0 14 * * *"
          - "0 16 * * *"
          - "0 18 * * *"
          - "0 20 * * *"
          - "0 22 * * *"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Determine Ad Content
        id: set-ad
        run: |
          case "${{ matrix.schedule }}" in
            "0 0 * * *") 
              echo "AD_CONTENT=${{ vars.AD_1 }}" >> $GITHUB_ENV
              echo "ACCOUNT_TOKEN=${{ secrets.ACCOUNT_1_TOKEN }}" >> $GITHUB_ENV
              ;;
            "0 2 * * *") 
              echo "AD_CONTENT=${{ vars.AD_2 }}" >> $GITHUB_ENV
              echo "ACCOUNT_TOKEN=${{ secrets.ACCOUNT_2_TOKEN }}" >> $GITHUB_ENV
              ;;
            "0 4 * * *") 
              echo "AD_CONTENT=${{ vars.AD_3 }}" >> $GITHUB_ENV
              echo "ACCOUNT_TOKEN=${{ secrets.ACCOUNT_3_TOKEN }}" >> $GITHUB_ENV
              ;;
            "0 6 * * *") 
              echo "AD_CONTENT=${{ vars.AD_4 }}" >> $GITHUB_ENV
              echo "ACCOUNT_TOKEN=${{ secrets.ACCOUNT_4_TOKEN }}" >> $GITHUB_ENV
              ;;
            "0 8 * * *") 
              echo "AD_CONTENT=${{ vars.AD_5 }}" >> $GITHUB_ENV
              echo "ACCOUNT_TOKEN=${{ secrets.ACCOUNT_1_TOKEN }}" >> $GITHUB_ENV
              ;;
            "0 10 * * *") 
              echo "AD_CONTENT=${{ vars.AD_6 }}" >> $GITHUB_ENV
              echo "ACCOUNT_TOKEN=${{ secrets.ACCOUNT_2_TOKEN }}" >> $GITHUB_ENV
              ;;
            "0 12 * * *") 
              echo "AD_CONTENT=${{ vars.AD_7 }}" >> $GITHUB_ENV
              echo "ACCOUNT_TOKEN=${{ secrets.ACCOUNT_3_TOKEN }}" >> $GITHUB_ENV
              ;;
            "0 14 * * *") 
              echo "AD_CONTENT=${{ vars.AD_8 }}" >> $GITHUB_ENV
              echo "ACCOUNT_TOKEN=${{ secrets.ACCOUNT_4_TOKEN }}" >> $GITHUB_ENV
              ;;
            "0 16 * * *") 
              echo "AD_CONTENT=${{ vars.AD_9 }}" >> $GITHUB_ENV
              echo "ACCOUNT_TOKEN=${{ secrets.ACCOUNT_1_TOKEN }}" >> $GITHUB_ENV
              ;;
            "0 18 * * *") 
              echo "AD_CONTENT=${{ vars.AD_10 }}" >> $GITHUB_ENV
              echo "ACCOUNT_TOKEN=${{ secrets.ACCOUNT_2_TOKEN }}" >> $GITHUB_ENV
              ;;
            "0 20 * * *") 
              echo "AD_CONTENT=${{ vars.AD_11 }}" >> $GITHUB_ENV
              echo "ACCOUNT_TOKEN=${{ secrets.ACCOUNT_3_TOKEN }}" >> $GITHUB_ENV
              ;;
            "0 22 * * *") 
              echo "AD_CONTENT=${{ vars.AD_12 }}" >> $GITHUB_ENV
              echo "ACCOUNT_TOKEN=${{ secrets.ACCOUNT_4_TOKEN }}" >> $GITHUB_ENV
              ;;
            *) 
              echo "No matching schedule. Exiting..."
              exit 1
              ;;
          esac

      - name: Debugging Variables
        run: |
          echo "Ad Content: ${{ env.AD_CONTENT }}"
          echo "Account Token: [HIDDEN]"

      - name: Post Ad
        run: python3 1.py "${{ env.AD_CONTENT }}" "${{ env.ACCOUNT_TOKEN }}" "${{ vars.DISCORD_URLS }}"