name: Ads Scheduler

on:
  schedule:
    - cron: "0 0 * * *"  # 00:00
    - cron: "0 2 * * *"  # 02:00
    - cron: "0 4 * * *"  # 04:00
    - cron: "0 6 * * *"  # 06:00
    - cron: "0 8 * * *"  # 08:00
    - cron: "0 10 * * *" # 10:00
    - cron: "0 12 * * *" # 12:00
    - cron: "0 14 * * *" # 14:00
    - cron: "0 16 * * *" # 16:00
    - cron: "0 18 * * *" # 18:00
    - cron: "0 20 * * *" # 20:00
    - cron: "0 22 * * *" # 22:00

jobs:
  post-ad:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - cron: "0 0 * * *"
            ad_variable: "AD_1"
            account: "ACCOUNT_1_TOKEN"
          - cron: "0 2 * * *"
            ad_variable: "AD_2"
            account: "ACCOUNT_2_TOKEN"
          - cron: "0 4 * * *"
            ad_variable: "AD_3"
            account: "ACCOUNT_3_TOKEN"
          - cron: "0 6 * * *"
            ad_variable: "AD_4"
            account: "ACCOUNT_4_TOKEN"
          - cron: "0 8 * * *"
            ad_variable: "AD_5"
            account: "ACCOUNT_1_TOKEN"
          - cron: "0 10 * * *"
            ad_variable: "AD_6"
            account: "ACCOUNT_2_TOKEN"
          - cron: "0 12 * * *"
            ad_variable: "AD_7"
            account: "ACCOUNT_3_TOKEN"
          - cron: "0 14 * * *"
            ad_variable: "AD_8"
            account: "ACCOUNT_4_TOKEN"
          - cron: "0 16 * * *"
            ad_variable: "AD_9"
            account: "ACCOUNT_1_TOKEN"
          - cron: "0 18 * * *"
            ad_variable: "AD_10"
            account: "ACCOUNT_2_TOKEN"
          - cron: "0 20 * * *"
            ad_variable: "AD_11"
            account: "ACCOUNT_3_TOKEN"
          - cron: "0 22 * * *"
            ad_variable: "AD_12"
            account: "ACCOUNT_4_TOKEN"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Load Ad Content and URLs
        id: load-variables
        run: |
          echo "AD_CONTENT=${{ vars[matrix.ad_variable] }}" >> $GITHUB_ENV
          echo "DISCORD_URLS=${{ vars.DISCORD_URLS }}" >> $GITHUB_ENV

      - name: Debugging Variables
        run: |
          echo "Ad Content: ${{ env.AD_CONTENT }}"
          echo "URLs: [HIDDEN]"
          echo "Account Token: [HIDDEN]"

      - name: Run Python Script
        run: python3 1.py "${{ env.AD_CONTENT }}" "${{ secrets[matrix.account] }}" "${{ env.DISCORD_URLS }}"
